### ISSUE TITLE
Not going to login page

### ISSUE THREAD

**Issue by adarshM84** [avinash-ghadshi/url-shortner#3]
Facing below issue :

1. Getting error at time of start server
 $ ./urlshortener 
bash: ./urlshortener: cannot execute binary file: Exec format error

2.After serving the client it is directly going to home tab not going on login tab

![image](https://github.com/user-attachments/assets/91ced0d6-f468-4339-ad49-7461c118eb73)

**Comment by avinash-ghadshi** [comment]
Thanks for raising the issue.
I have addressed this login issue.
Still UI is under development.

It seems that, created binary is not working properly for other than MacOS.
I have updated the README document. You can rebuild binary by referring README.
